version: "3.3"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    volumes:
      - ./api:/usr/src/app
    depends_on:
      db:
        condition: service_started
  db:
    container_name: postgres
    build: ./db
    ports:
      - "5432:5432"
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres